INC3: Add service backbone
bigbag/go-musthave-shortener pull request #1
Opened 2022-02-19 16:04 UTC by bigbag

2022-02-20 15:39 UTC, ASPecherkin requested changes
Всё хорошо, небольшие правки и можно будет мержить

2022-02-20 15:39 UTC, ASPecherkin commented on cmd/shortener/main.go
> +	log logrus.StdLogger
А есть ли смысл в глобальной переменной logger, хотя ниже ты его передаёшь как зависимость в 
```go
apiServer = app.New(logger, cfg)
``` 
напрямую?

лучше всего не использовать глобальные переменные вообще, у тебя есть функции New под каждый из объектов - возвращай нужные объекты и передавай напрямую как зависимость

2022-02-20 15:39 UTC, ASPecherkin commented on cmd/shortener/main.go
> +func _init() {
Ты можешь удалить эту функцию , а вычитывание config.New перенести в main и уже готовый объект использовать где он нужен - например передать в создание logger

Кроме того - в go не принято название функций с _

2022-02-20 15:39 UTC, ASPecherkin commented on internal/url/repository.go
> +func NewURLRepository() URLRepository {
Так как реализация сейчас только одна - лучше возвращать указатель на тип storageRepository
Его можно сделать публичным, проблемы тут нет - принимающая сторона описывает аргумент, как строгий интерфейс  - она не сможет использовать методы, которые не объявлены в интерфейсе

2022-02-20 16:30 UTC, bigbag commented on cmd/shortener/main.go
> +	log logrus.StdLogger
Исправил

2022-02-20 16:31 UTC, bigbag commented on cmd/shortener/main.go
> +func _init() {
Исправил

2022-02-20 16:33 UTC, bigbag commented on internal/url/repository.go
> +func NewURLRepository() URLRepository {
Если можно хотелось бы оставить storageRepository приватным, понимаю что в нашем случае это излишне, но мне кажется так более readable.

2022-02-21 19:12 UTC, ASPecherkin approved these changes
Остался минорный вопрос , не влияет на дальнейшую разработку

2022-02-21 19:12 UTC, ASPecherkin commented on internal/url/handler.go
> +	fullURL := string(c.Body()[:])
а зачем здесь [:]? c какой целью?

2022-02-21 19:12 UTC, ASPecherkin commented on internal/url/repository.go
> +func NewURLRepository() URLRepository {
в целом можно так оставить, если таким образом хочешь строгости соблюдения интерфейса 
Если по итогу проекта это не будет помехой - хорошо

Но да, отмечу - в Go принят другой способ ограничения контракта интерфейса

2022-02-22 06:31 UTC, bigbag commented on internal/url/repository.go
> +func NewURLRepository() URLRepository {
А можешь скинуть пример?

2022-02-22 06:32 UTC, bigbag commented on internal/url/handler.go
> +	fullURL := string(c.Body()[:])
Исправил

2022-02-22 06:33 UTC, bigbag commented on internal/url/repository.go
> +func NewURLRepository() URLRepository {
Я шел по аналогии с https://github.com/gofiber/recipes/tree/master/docker-mariadb-clean-arch/internal/city

2022-02-22 08:42 UTC, merged